export const COUNTRY_MAP = {
  // 🇪🇺 Europa
  Germany: { name: "Alemania", iso: "de" },
  Spain: { name: "España", iso: "es" },
  France: { name: "Francia", iso: "fr" },
  Italy: { name: "Italia", iso: "it" },
  England: { name: "Inglaterra", iso: "gb" },
  Portugal: { name: "Portugal", iso: "pt" },
  Netherlands: { name: "Países Bajos", iso: "nl" },
  Belgium: { name: "Bélgica", iso: "be" },
  Switzerland: { name: "Suiza", iso: "ch" },
  Austria: { name: "Austria", iso: "at" },
  Denmark: { name: "Dinamarca", iso: "dk" },
  Sweden: { name: "Suecia", iso: "se" },
  Norway: { name: "Noruega", iso: "no" },
  Finland: { name: "Finlandia", iso: "fi" },
  Poland: { name: "Polonia", iso: "pl" },
  CzechRepublic: { name: "República Checa", iso: "cz" },
  Hungary: { name: "Hungría", iso: "hu" },
  Croatia: { name: "Croacia", iso: "hr" },
  Serbia: { name: "Serbia", iso: "rs" },
  Slovenia: { name: "Eslovenia", iso: "si" },
  Slovakia: { name: "Eslovaquia", iso: "sk" },
  Greece: { name: "Grecia", iso: "gr" },
  Turkey: { name: "Turquía", iso: "tr" },
  Russia: { name: "Rusia", iso: "ru" },
  Ukraine: { name: "Ucrania", iso: "ua" },
  Romania: { name: "Rumania", iso: "ro" },
  Bulgaria: { name: "Bulgaria", iso: "bg" },
  Scotland: { name: "Escocia", iso: "gb-sct" },
  Ireland: { name: "Irlanda", iso: "ie" },
  Wales: { name: "Gales", iso: "gb-wls" },
  Iceland: { name: "Islandia", iso: "is" },
  BosniaHerzegovina: { name: "Bosnia y Herzegovina", iso: "ba" },

  // 🇸🇪 Escandinavia y bálticos
  Lithuania: { name: "Lituania", iso: "lt" },
  Latvia: { name: "Letonia", iso: "lv" },
  Estonia: { name: "Estonia", iso: "ee" },

  // 🇦🇷 Sudamérica
  Argentina: { name: "Argentina", iso: "ar" },
  Brazil: { name: "Brasil", iso: "br" },
  Uruguay: { name: "Uruguay", iso: "uy" },
  Chile: { name: "Chile", iso: "cl" },
  Paraguay: { name: "Paraguay", iso: "py" },
  Bolivia: { name: "Bolivia", iso: "bo" },
  Peru: { name: "Perú", iso: "pe" },
  Colombia: { name: "Colombia", iso: "co" },
  Ecuador: { name: "Ecuador", iso: "ec" },
  Venezuela: { name: "Venezuela", iso: "ve" },

  // 🇲🇽 Norteamérica / Centroamérica / Caribe
  Mexico: { name: "México", iso: "mx" },
  "United States": { name: "Estados Unidos", iso: "us" },
  Canada: { name: "Canadá", iso: "ca" },
  CostaRica: { name: "Costa Rica", iso: "cr" },
  Honduras: { name: "Honduras", iso: "hn" },
  Panama: { name: "Panamá", iso: "pa" },
  Guatemala: { name: "Guatemala", iso: "gt" },
  ElSalvador: { name: "El Salvador", iso: "sv" },
  Jamaica: { name: "Jamaica", iso: "jm" },

  // 🇮🇳 Asia
  Japan: { name: "Japón", iso: "jp" },
  SouthKorea: { name: "Corea del Sur", iso: "kr" },
  China: { name: "China", iso: "cn" },
  India: { name: "India", iso: "in" },
  Iran: { name: "Irán", iso: "ir" },
  SaudiArabia: { name: "Arabia Saudita", iso: "sa" },
  Qatar: { name: "Catar", iso: "qa" },
  UnitedArabEmirates: { name: "Emiratos Árabes Unidos", iso: "ae" },
  Israel: { name: "Israel", iso: "il" },
  Uzbekistan: { name: "Uzbekistán", iso: "uz" },
  Thailand: { name: "Tailandia", iso: "th" },
  Indonesia: { name: "Indonesia", iso: "id" },
  Malaysia: { name: "Malasia", iso: "my" },
  Vietnam: { name: "Vietnam", iso: "vn" },
  Kazakhstan: { name: "Kazajistán", iso: "kz" },

  // 🌍 África
  Egypt: { name: "Egipto", iso: "eg" },
  SouthAfrica: { name: "Sudáfrica", iso: "za" },
  Morocco: { name: "Marruecos", iso: "ma" },
  Algeria: { name: "Argelia", iso: "dz" },
  Tunisia: { name: "Túnez", iso: "tn" },
  Nigeria: { name: "Nigeria", iso: "ng" },
  Ghana: { name: "Ghana", iso: "gh" },
  IvoryCoast: { name: "Costa de Marfil", iso: "ci" },
  Cameroon: { name: "Camerún", iso: "cm" },
  Senegal: { name: "Senegal", iso: "sn" },
  DRCongo: { name: "Congo (R.D.)", iso: "cd" },

  // 🌏 Oceanía
  Australia: { name: "Australia", iso: "au" },
  NewZealand: { name: "Nueva Zelanda", iso: "nz" },
};
